#!/bin/sh

set -e
set -x

export TESTDIR=/builds/test
export GRADLE_USER_HOME=$TESTDIR/.gradle

mkdir -p $TESTDIR
cd $TESTDIR

fdroid nightly -h
fdroid init

git clone --depth 1 https://gitlab.com/fdroid/fdroidclient.git
cd fdroidclient
./tools/check-format-strings.py

cat /proc/meminfo
maxmem=$(expr $(sed -n 's,^MemAvailable:[^0-9]*\([0-9][0-9]*\)[^0-9]*$,\1,p' /proc/meminfo) / 1024 / 2 / 1024 \* 1024)
printf "\norg.gradle.jvmargs=-Xmx${maxmem}m -XX:MaxPermSize=${maxmem}m\norg.gradle.daemon=false\norg.gradle.parallel=false\n" >> local.properties

# fork after every test to try to avoid crashes
sed -i 's,forkEvery.*,forkEvery = 1,' app/build.gradle

./gradlew testFullDebugUnitTest
test -z "$DEBUG_KEYSTORE" || fdroid nightly -v

emulator -accel-check || true
grep -v '^License' $ANDROID_HOME/tools/source.properties \
     $ANDROID_HOME/emulator/source.properties \


avdmanager list avd
adb start-server

export CI_JOB_NAME="test 23 default x86_64"
start-emulator
wait-for-emulator

export FLAG=-Pandroid.testInstrumentationRunnerArguments.notAnnotation=androidx.test.filters.LargeTest
./gradlew connectedFullDebugAndroidTest $FLAG \
    || (adb -e logcat -d '*:W'; exit 1)

du -sh --one-file-system /* || true
du -sh --one-file-system /var/* || true
du -sh --one-file-system $ANDROID_HOME/* || true

apt-get -qy update
apt-get -qy install procps
ps auxww
