#!/bin/sh

set -e
set -x

export TESTDIR=/builds/test
export GRADLE_USER_HOME=$TESTDIR/.gradle

mkdir -p $TESTDIR
cd $TESTDIR

fdroid nightly -h
fdroid init

git clone --depth 1 https://gitlab.com/fdroid/fdroidclient.git
cd fdroidclient
./tools/check-format-strings.py
./gradlew test  || {
    for log in `find app/build/reports -name '*ml'`; do
        echo "read $log here:"
        (cat "$log" | curl --silent -F 'clbin=<-' https://clbin.com) || true
    done
    exit 1
}

emulator -accel-check || true
grep -v '^License' $ANDROID_HOME/tools/source.properties \
     $ANDROID_HOME/emulator/source.properties \
     $ANDROID_HOME/system-images/android-*/*/*/source.properties

avdmanager list avd
adb start-server

export CI_JOB_NAME="test $AVD_SDK $AVD_TAG $AVD_ARCH"
start-emulator
wait-for-emulator

./gradlew connectedFullDebugAndroidTest -Pandroid.testInstrumentationRunnerArguments.notAnnotation=android.support.test.filters.LargeTest \
    || (adb -e logcat -d '*:W'; exit 1)

du -sh --one-file-system /* || true
du -sh --one-file-system /var/* || true
du -sh --one-file-system $ANDROID_HOME/* || true

apt-get -qy update
apt-get -qy install procps
ps auxww
